### ISSUE TITLE
Camera queries can be simplified

### ISSUE THREAD

**Issue by tguichaoua** [sburris0/bevy_flycam#14]
Following queries can be simplified using [`With` filter](https://docs.rs/bevy/latest/bevy/prelude/struct.Query.html#query-filtering), since `FlyCam` is just a marker component.

https://github.com/sburris0/bevy_flycam/blob/100a15d412b2419e463dc73fd0de50ef4b31b97b/src/lib.rs#L59-L62

https://github.com/sburris0/bevy_flycam/blob/100a15d412b2419e463dc73fd0de50ef4b31b97b/src/lib.rs#L94-L97

```rs
     mut query: Query<&mut Transform, With<FlyCam>>,
 ) { 
     let window = windows.get_primary().unwrap(); 
     for mut transform in query.iter_mut() { 
```

**Comment by BlackPhlox** [comment]
Closed by #16 being merged 🚀
