### ISSUE TITLE
intentional position and orientation

### ISSUE THREAD

**Issue by DerKarlos** [sburris0/bevy_flycam#17]
It would be nice, if the initial position and orientation could be set by the user.
May be the MovementSettings could become CameraSettings?
(And thank you for the crate, it gave me a fast help)

**Comment by sburris0** [comment]
Hello, this is what `NoCameraPlayerPlugin` is useful for. You can do whatever you want with the camera and attach controls to it. An example of this is in `examples/scroll.rs` around line 20 and 58-65

https://github.com/sburris0/bevy_flycam/blob/075904bff5d4f1af1499f5217d9284642d27b93a/examples/scroll.rs

I'm glad this crate has been useful to you

**Comment by MiniaczQ** [comment]
While the position can be set, I don't think initial pitch an yaw are derived from initial transform.
I'd need a little bit more testing to be sure, but with my current setup I start by looking at an object
and the smallest mouse movement rotates camera to where I can no longer see it.

**Comment by Neopallium** [comment]
@MiniaczQ I had that same issue.  See PR #21 for a fix.
