### ISSUE TITLE
Upgrade to Bevy 0.13

### ISSUE THREAD

**Issue by arjpeg** [sburris0/bevy_flycam#44]
Bevy 0.13 recently released, and it would be great to use this crate with it. I'm not fully sure how hard upgrading it would be, but shouldn't be too hard in theory.

If you want, I can take a shot at implementing this, and will create a pr.

Thanks

**Comment by sburris0** [comment]
There is a PR open at https://github.com/sburris0/bevy_flycam/pull/43, testing/reviews would be very helpful

I will merge it soon after I solve system issues preventing me from testing myself

**Comment by sburris0** [comment]
merged
