### ISSUE TITLE
Inconsistent sensitivity between pitch and yaw

### ISSUE THREAD

**Issue by TarekAS** [sburris0/bevy_flycam#9]
Looking up and down (pitch) is a bit slower than left and right (yaw), which feels weird in my experience. It a lot slower the more wide the window (maybe too slow if fullscreen on a 21:9).

I think this is caused by multiplying the sensitivity and delta by the `window.height()` or `* window.width()`. After removing this multiplication, I get a consistent sensitivity in all directions. May I ask why this is being done?

**Comment by sburris0** [comment]
It was added because playing in a small window yielded ridiculous sensitivity, if I remember correctly.

**Comment by sburris0** [comment]
It probably would.
I'll hopefully get around to fix it soon, unless someone else does it first.

**Comment by sburris0** [comment]
Fixed in cf8ab02
